// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	character "github.com/gclamigueiro/dragon-ball-api/internal/character"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetAll provides a mock function with no fields
func (_m *Service) GetAll() ([]*character.Character, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*character.Character
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*character.Character, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*character.Character); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*character.Character)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByName provides a mock function with given fields: name
func (_m *Service) GetByName(name string) (*character.Character, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *character.Character
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*character.Character, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *character.Character); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*character.Character)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
