// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	dragonball "github.com/gclamigueiro/dragon-ball-api/internal/client/dragonball"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// GetCharacterByName provides a mock function with given fields: name
func (_m *Client) GetCharacterByName(name string) (*dragonball.Character, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetCharacterByName")
	}

	var r0 *dragonball.Character
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*dragonball.Character, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *dragonball.Character); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dragonball.Character)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
